---
title: "Interesting Places"
author: "Jorge Sauma"
date: "January 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## San Francisco landmarks

```{r echo=FALSE}
library(leaflet)
#SFIcons <- icons(
#  iconUrl = c("http://theargonauts.com/design/logos/images/logo_26_b.jpg", ""),
#  iconWidth = 60, iconHeight = 60,
#  iconAnchorX = 31*215/230/2, iconAnchorY = 16
#)
SFIcons <- iconList(
  gg = makeIcon("http://theargonauts.com/design/logos/images/logo_26_b.jpg", "ferry-18@2x.png", iconWidth=60, iconHeight=60),
  al = makeIcon("http://clipart.coolclips.com/480/vectors/tf05207/CoolClips_vc022820.png", iconWidth=60, iconHeight=60),
  fw= makeIcon("http://bestwesterngilroy.com/wp-content/uploads/2012/02/logo-10.jpg", iconWidth=180/2, iconHeight=143/2),
  ls = makeIcon("http://clipground.com/images/lombard-street-clipart-4.jpg", iconWidth=236/4, iconHeight=360/4),
  att = makeIcon("http://thescore-api-artifacts.s3.amazonaws.com/baseball/team/28/small_logo.png", iconWidth=500/7, iconHeight=500/7),
  tp = makeIcon("http://lh6.googleusercontent.com/-nGrJ_y2nBhA/AAAAAAAAAAI/AAAAAAAAAsQ/gITitNWB1XQ/photo.jpg", iconWidth=256/4, iconHeight=256/4)
    )

SFLatLong <- data.frame(
  lat = c(37.8199, 37.8270, 37.8080, 37.773972, 37.7786, 37.751586275),
  lng = c(-122.4783, -122.4230, -122.4177, -122.431297, -122.3893, -122.4477))

SFLatLong %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = SFIcons[c("gg", "al", "fw", "ls", "att", "tp")])
```

##Date: January, 25th, 2018##

```{r}
date()
```
